# Generated by Django 4.1.2 on 2022-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('BUR', 'Basic User'), ('PSA', 'Pacer Superadmin')], default=None, max_length=3, null=True, verbose_name='Role'),
        ),
    ]
