# Generated by Django 4.1.2 on 2022-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Record', 'verbose_name_plural': 'Daily Records'},
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
